// this file defined all the error codes that can occurr in the application 
export const ErrorCodes =  {
    BAD_REQUEST : 400,  // REQUEST WAS BAD
    NOT_FOUND : 404,  // DATA/RECORD NOT FOUNND 
    CONFLICT : 409,  // DUPLICATE ENTRIES FOUND
    INTERNAL_ERROR : 500, // SOME BAD THING HAPPENED ON THE SERVER SIDE
    SUCCESS : 200,  // THE API RESQUEST WAS SUCCESS
    CREATED : 201,  // WAS ABLE TO SUCCESSFULLY CREATE THE RECORD IN DB
    FORBIDDEN : 403, // AUTHENTICATION BUT NO PERMISSION
}