// this file defined all the error codes that can occurr in the application 
export const StatusCodes =  {
    BAD_REQUEST_400 : 400,  // REQUEST WAS BAD
    NOT_FOUND_404 : 404,  // DATA/RECORD NOT FOUNND 
    CONFLICT_409 : 409,  // DUPLICATE ENTRIES FOUND
    INTERNAL_ERROR_500 : 500, // SOME BAD THING HAPPENED ON THE SERVER SIDE
    SUCCESS_200 : 200,  // THE API RESQUEST WAS SUCCESS
    CREATED_201 : 201,  // WAS ABLE TO SUCCESSFULLY CREATE THE RECORD IN DB
    FORBIDDEN_403 : 403, // AUTHENTICATION BUT NO PERMISSION
    NOT_AUTHORIZED_401 : 401
}